name: Daily Commit

on:
  schedule:
    - cron: '0 9 * * *'  # Runs daily at 9 AM UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Make dummy change
      run: |
        echo "✅ $(date)" >> log.txt
        git config --global user.name 'Prabhas777'
        git config --global user.email 'prabhas.sama0008@gmail.com'
        git add log.txt
        git commit -m "Daily update"
        git push
